name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  allowedStatusCodes:
    description: "Status code which links are allowed to return"
    required: true
    default: 200

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
